services:
  douglas:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ../../../AUV-2024
        target: /AUV-2024
    image: "mcgillrobotics/auv_2024:jetson"
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on

    runtime: nvidia
    command: bash -c ${OVERRIDE_COMMAND:-"tail -f /dev/null"}
    network_mode: host
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  zed:
    volumes:
      - /dev:/dev
    image: "mcgillrobotics/auv_2024:zed"
    build:
      context: ../../../AUV-2024
      dockerfile: Docker/jetson/Dockerfile.zed
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on
    runtime: nvidia
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  bridge:
    image: "mcgillrobotics/auv_2024:rosbridge"
    build:
      context: ../../../AUV-2024
      dockerfile: Docker/jetson/Dockerfile.bridge
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: host
